name: Publish TELOS JSON

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write
 


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Generate telos.json
        run: |
          mkdir -p public/.well-known
          python scripts/telos_md_to_json.py personal_telos.md -o public/.well-known/telos.json
      - name: Install cosign
        uses: sigstore/cosign-installer@v3
      - name: Sign telos.json
        run: |
          cosign sign-blob --yes --output-signature public/.well-known/telos.json.sig public/.well-known/telos.json
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
